### PR TITLE
Implement stringer interface

### LINKED ISSUE #745: Compilation error
**Describe the bug**
Hi there,
Your module requires github.com/golang-sql/sqlexp
This module had no go.mod file until now, and one was added today (https://github.com/golang-sql/sqlexp/blob/master/go.mod) for go 1.16.
After running `go get -u ./...` on my module (which requires yours) I saw:
```
$ go get -u ./...
go: upgraded github.com/golang-sql/sqlexp v0.0.0-20170517235910-f1bb20e5a188 => v0.0.0-20220518152126-d42ba59f5c11
...
```
Trying to build my module, I get the following compilation error:
```
# github.com/denisenkom/go-mssqldb
../../../../pkg/mod/github.com/denisenkom/go-mssqldb@v0.12.0/token.go:790:79: cannot use info.Message (variable of type string) as type fmt.Stringer in struct literal:
	string does not implement fmt.Stringer (missing String method)

Compilation finished with exit code 2
```

**To Reproduce**
See above.
**Expected behavior**
Code that compiles. Thank you!

### Further technical details
Operating system: Ubuntu 20.04.4
Golang version: go1.18.2 linux/amd64

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by sushilkg**
Fixes #745.

Caused by https://github.com/golang-sql/sqlexp/commit/d42ba59f5c11011b1df5abc536ee75821c22bdac.

### CODE REVIEW

**Review by kardianos — APPROVED** [review]

**Comment by shueybubbles** [comment]
Could you port this to the microsoft fork? github.com/microsoft/go-mssqldb

**Comment by josheyr** [comment]
Causing build errors in my project:
`# github.com/denisenkom/go-mssqldb
..\..\go\pkg\mod\github.com\denisenkom\go-mssqldb@v0.12.0\token.go:790:79: cannot use info.Message (variable of type string) as type fmt.Stringer in struct literal:
        string does not implement fmt.Stringer (missing String method)`
Let me know if more details needed
